plugins {
    kotlin("jvm") version "1.9.20"
    `java-gradle-plugin`
    id("com.gradle.plugin-publish") version "1.2.1"
    kotlin("plugin.serialization") version "1.9.20"
    jacoco
}

group = "com.obvyr"
version = (findProperty("pluginVersion") as String?) ?: "1.0.0"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation("org.apache.commons:commons-compress:1.26.2")
    implementation("com.github.luben:zstd-jni:1.5.6-3")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")

    testImplementation(gradleTestKit())
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
    testImplementation("com.squareup.okhttp3:okhttp-tls:4.12.0")
    testImplementation("org.assertj:assertj-core:3.25.3")
    testImplementation("io.mockk:mockk:1.13.8")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.22")
}

gradlePlugin {
    website.set("https://github.com/obvyr/obvyr-gradle#readme")
    vcsUrl.set("https://github.com/obvyr/obvyr-gradle")

    plugins {
        create("obvyrPlugin") {
            id = "com.obvyr.gradle"
            implementationClass = "com.obvyr.gradle.ObvyrPlugin"
            displayName = "Obvyr Test Execution Tracking Plugin"
            description = "Gradle plugin for collecting and submitting test execution data to Obvyr"
            tags.set(listOf("testing", "observability", "metrics", "reporting"))
        }
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required = true
    }
    // Exclude the anonymous X509TrustManager used for verifySsl=false. Its
    // checkClientTrusted method is a required interface stub that is only ever
    // invoked server-side during mutual TLS; it is structurally unreachable in a
    // client-only SSL context and therefore not meaningful to measure.
    classDirectories.setFrom(
        files(classDirectories.files.map {
            fileTree(it) {
                // checkClientTrusted on the trust-all X509TrustManager is only invoked
                // server-side during mutual TLS; unreachable in a client-only SSL context.
                exclude("**/ObvyrApiClient\$buildClient\$trustAllCerts\$1.class")
                // Generated by kotlinx-serialization. The plugin only ever serialises
                // CommandJson; the deserialise and childSerializers methods are dead code
                // by design and cannot be exercised without introducing a deserialisation
                // path that serves no production purpose.
                exclude("**/CommandJson\$\$serializer.class")
            }
        }),
    )
}

tasks.withType<Copy> {
    duplicatesStrategy = DuplicatesStrategy.WARN
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "17"
    }
}